require 'hashmake'
require 'sigproc/version'

require 'sigproc/core/limiters'
require 'sigproc/core/constants'

require 'sigproc/lib/interpolation'
require 'sigproc/lib/circular_buffer'
require 'sigproc/lib/delay_line'
require 'sigproc/lib/gain'
require 'sigproc/lib/oscillator'
require 'sigproc/lib/biquad_filter'
require 'sigproc/lib/cookbook_allpass_filter'
require 'sigproc/lib/cookbook_bandpass_filter'
require 'sigproc/lib/cookbook_highpass_filter'
require 'sigproc/lib/cookbook_lowpass_filter'
require 'sigproc/lib/cookbook_notch_filter'
require 'sigproc/lib/envelope_detector'
require 'sigproc/lib/saturation'

require 'sigproc/blocks/gain_block'
require 'sigproc/blocks/delay_block'
require 'sigproc/blocks/oscillator_block'
require 'sigproc/blocks/file_out_block'
