require 'sigproc/version'

require 'sigproc/core/hash_make'
require 'sigproc/core/limiters'
require 'sigproc/core/constants'

require 'sigproc/processing/interpolation'
require 'sigproc/processing/circular_buffer'
require 'sigproc/processing/delay_line'
require 'sigproc/processing/gain'
require 'sigproc/processing/oscillator'
require 'sigproc/processing/biquad_filter'
require 'sigproc/processing/cookbook_allpass_filter'
require 'sigproc/processing/cookbook_bandpass_filter'
require 'sigproc/processing/cookbook_highpass_filter'
require 'sigproc/processing/cookbook_lowpass_filter'
require 'sigproc/processing/cookbook_notch_filter'
require 'sigproc/processing/envelope_detector'
require 'sigproc/processing/saturation'

require 'sigproc/network/signal_in_port'
require 'sigproc/network/signal_out_port'
require 'sigproc/network/processor'