require 'hashmake'
require 'spcore/version'

require 'spcore/core/limiters'
require 'spcore/core/constants'
require 'spcore/core/window'

require 'spcore/lib/interpolation'
require 'spcore/lib/circular_buffer'
require 'spcore/lib/delay_line'
require 'spcore/lib/gain'
require 'spcore/lib/oscillator'
require 'spcore/lib/biquad_filter'
require 'spcore/lib/cookbook_allpass_filter'
require 'spcore/lib/cookbook_bandpass_filter'
require 'spcore/lib/cookbook_highpass_filter'
require 'spcore/lib/cookbook_lowpass_filter'
require 'spcore/lib/cookbook_notch_filter'
require 'spcore/lib/envelope_detector'
require 'spcore/lib/saturation'
